<?php
use CodeIgniter\Router\RouteCollection;
/** @var RouteCollection $routes */
$routes->setAutoRoute(false);
$routes->get('/', 'CatalogoController::index');
$routes->get('catalogo', 'CatalogoController::index');
$routes->get('catalogo/json/(:segment)', 'CatalogoController::json/$1');
$routes->get('catalogo/(:segment)', 'CatalogoController::show/$1');
$routes->get('politicas-terminos-y-condiciones', 'PaginasController::terminos');
$routes->get('login', 'Auth::login');
$routes->post('login', 'Auth::doLogin');
$routes->get('register', 'Auth::register');
$routes->post('register', 'Auth::doRegister');
$routes->get('forgot', 'Auth::forgot');
$routes->post('forgot', 'Auth::sendReset');
$routes->get('reset/(:segment)', 'Auth::reset/$1');
$routes->post('reset', 'Auth::doReset');
$routes->post('logout', 'Auth::logout', ['filter' => 'auth']);
$routes->get('dashboard', 'Dashboard::index', ['filter' => 'auth']);
$routes->get('inventario/ubicaciones', 'WarehouseController::index', ['filter' => 'permission:inventory.view']);
$routes->post('inventario/sedes', 'WarehouseController::createSite', ['filter' => 'permission:inventory.adjust']);
$routes->post('inventario/almacenes', 'WarehouseController::createWarehouse', ['filter' => 'permission:inventory.adjust']);
$routes->post('inventario/ubicaciones', 'WarehouseController::createLocation', ['filter' => 'permission:inventory.adjust']);
$routes->post('inventario/estructura/estado', 'WarehouseController::changeStatus', ['filter' => 'permission:inventory.adjust']);
$routes->get('admin/dashboard', 'Admin\DashboardController::index', ['filter' => 'permission:dashboard.view,orders.view']);
$routes->get('admin/accesos', 'AccessController::index', ['filter' => 'permission:access.manage']);
$routes->post('admin/accesos', 'AccessController::update', ['filter' => 'permission:access.manage']);
$routes->get('carretilla', 'CarretillaController::index', ['filter' => 'auth']);
$routes->post('carretilla/agregar', 'CarretillaController::add', ['filter' => 'auth']);
$routes->post('carretilla/update', 'CarretillaController::update', ['filter' => 'auth']);
$routes->post('carretilla/remove/(:num)', 'CarretillaController::remove/$1', ['filter' => 'auth']);
$routes->post('carretilla/clear', 'CarretillaController::clear', ['filter' => 'auth']);
$routes->get('carretilla/checkout', 'CarretillaController::checkout', ['filter' => 'auth']);
$routes->post('carretilla/place-order', 'CarretillaController::placeOrder', ['filter' => 'auth']);
$routes->get('pedidos', 'PedidoController::index', ['filter' => 'auth']);
$routes->get('pedidos/(:num)', 'PedidoController::ver/$1', ['filter' => 'auth']);
$routes->post('pedidos/cambiar-estado/(:num)', 'PedidoController::cambiarEstado/$1', ['filter' => 'permission:orders.change']);
$routes->get('productos', 'ProductoController::index', ['filter' => 'permission:products.manage']);
$routes->post('productos/eliminar/(:num)', 'ProductoController::eliminar/$1', ['filter' => 'permission:products.manage']);
$routes->get('productos/kardex/(:num)', 'ProductoController::kardex/$1', ['filter' => 'permission:inventory.view']);
$routes->post('productos/kardex/(:num)/movimiento', 'ProductoController::movimiento/$1', ['filter' => 'permission:inventory.adjust']);
$routes->get('productos/kardex/(:num)/export', 'ProductoController::exportKardex/$1', ['filter' => 'permission:inventory.view']);
$routes->get('productos/reporte', 'PedidoController::reporte', ['filter' => 'permission:orders.view']);
$routes->get('productos/reporte/export', 'PedidoController::exportReporte', ['filter' => 'permission:orders.view']);
$routes->get('productos/(:num)/imagenes', 'ProductoController::imagenes/$1', ['filter' => 'permission:products.manage']);
$routes->post('productos/(:num)/imagenes/subir', 'ProductoController::subirImagen/$1', ['filter' => 'permission:products.manage']);
$routes->post('productos/(:num)/imagenes/(:num)/principal', 'ProductoController::imagenPrincipal/$1/$2', ['filter' => 'permission:products.manage']);
$routes->post('productos/(:num)/imagenes/(:num)/eliminar', 'ProductoController::eliminarImagen/$1/$2', ['filter' => 'permission:products.manage']);
$routes->match(['get', 'post'], 'productos/crear', 'ProductoController::crear', ['filter' => 'permission:products.manage,prices.manage,inventory.adjust']);
$routes->match(['get', 'post'], 'productos/editar/(:num)', 'ProductoController::editar/$1', ['filter' => 'permission:products.manage,prices.manage,inventory.adjust']);
$routes->match(['get', 'post'], 'productos/escalas/(:num)', 'ProductoController::escalas/$1', ['filter' => 'permission:prices.manage']);
$routes->get('productos/importar', 'ProductoImportController::form', ['filter' => 'permission:inventory.import,products.manage,prices.manage']);
$routes->get('productos/importar/plantilla', 'ProductoImportController::template', ['filter' => 'permission:inventory.import,products.manage,prices.manage']);
$routes->post('productos/importar/previsualizar', 'ProductoImportController::preview', ['filter' => 'permission:inventory.import,products.manage,prices.manage']);
$routes->post('productos/importar/procesar', 'ProductoImportController::process', ['filter' => 'permission:inventory.import,products.manage,prices.manage']);
// No demo, migration or seeder HTTP endpoints. Guest checkout arrives in I5.
