<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>
<link rel="stylesheet" href="<?= base_url('assets/css/commerce-admin.css') ?>">
<?php $value=fn($key,$default='')=>old($key)??$default;$errors=session('errors')??[]; ?>
<main class="commerce-page">
<header class="commerce-page-heading"><div><p class="commerce-eyebrow">CATÁLOGO / NUEVO REGISTRO</p><h1>Crear producto</h1><p>Registra la identidad comercial. Después podrás definir unidad, fardo, caja y sus precios.</p></div><a href="<?= site_url('productos') ?>">Volver al catálogo →</a></header>
<?php if($errors): ?><section class="commerce-errors" role="alert"><strong>Revisa la información indicada</strong><ul><?php foreach($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></section><?php endif ?>
<form method="post" action="<?= site_url('productos/crear') ?>" enctype="multipart/form-data" class="commerce-form-layout" novalidate><?= csrf_field() ?>
<div class="commerce-form-main">
<section class="commerce-card"><div class="commerce-section-heading"><div><p class="commerce-eyebrow">01 / IDENTIDAD</p><h2>Información principal</h2></div><p>Datos que permiten encontrar y reconocer el producto.</p></div><div class="commerce-fields">
<label>SKU <input name="sku" maxlength="50" value="<?= esc($value('sku')) ?>" placeholder="Ej.: COC-001" required><small>Código único, estable y fácil de buscar.</small></label>
<label>Nombre del producto <input id="nombre" name="nombre" maxlength="150" value="<?= esc($value('nombre')) ?>" placeholder="Ej.: Juego de cubiertos" required><small>Enlace previsto: <span id="slug-preview">producto</span></small></label>
<label class="is-wide">Descripción <textarea name="descripcion" rows="4" placeholder="Material, medidas, color y detalles útiles para venderlo."><?= esc($value('descripcion')) ?></textarea></label></div></section>
<section class="commerce-card"><div class="commerce-section-heading"><div><p class="commerce-eyebrow">02 / IMÁGENES</p><h2>Presentación visual</h2></div><p>La primera imagen local quedará como principal.</p></div><div class="commerce-fields">
<label class="is-wide">URL de imagen <input id="imagen_url" name="imagen_url" value="<?= esc($value('imagen_url')) ?>" placeholder="https://.../producto.webp"><small>Opcional si cargarás archivos desde el equipo.</small></label>
<div class="commerce-image-preview"><img id="preview-img" src="<?= $value('imagen_url')?esc($value('imagen_url')):base_url('assets/placeholder-product.png') ?>" alt="Vista previa del producto"><div><strong>Vista previa</strong><p>Usa fotografías claras, con fondo limpio y encuadre consistente.</p></div></div>
<label class="is-wide commerce-file">Archivos JPG, PNG o WebP <input id="imagenes" name="imagenes[]" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" multiple><small>Hasta 5 imágenes de 4 MB cada una.</small></label><div id="imagenes-preview" class="commerce-thumbnails"></div></div></section></div>
<aside class="commerce-form-side"><section class="commerce-card commerce-side-card"><p class="commerce-eyebrow">03 / CONFIGURACIÓN INICIAL</p><h2>Datos provisionales</h2><p>Estos valores mantienen compatibilidad con el catálogo anterior.</p><label>Precio base ($)<input id="precio_base" type="number" step="0.01" min="0" name="precio_base" value="<?= esc($value('precio_base','0.00')) ?>" required><small>Luego se reemplazará operativamente por precios de presentación.</small></label><label>Stock inicial<input id="stock" type="number" min="0" step="1" name="stock" value="<?= esc($value('stock','0')) ?>"><small>Será migrado al inventario trazable en un corte posterior.</small></label><label class="commerce-switch"><input type="checkbox" name="is_activo" value="1" <?= $value('is_activo','1')?'checked':'' ?>><span></span><div><strong>Producto activo</strong><small>Disponible para los procesos autorizados.</small></div></label></section>
<div class="commerce-submit"><button class="commerce-primary" type="submit">Guardar producto</button><a href="<?= site_url('productos') ?>">Cancelar</a><small>Al guardar podrás configurar sus presentaciones.</small></div></aside></form></main>
<script src="<?= base_url('assets/js/product-form.js') ?>"></script>
<?= $this->endSection() ?>
