<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>
<link rel="stylesheet" href="<?= base_url('assets/vendor/sweetalert2/sweetalert2.min.css') ?>"><link rel="stylesheet" href="<?= base_url('assets/css/commerce-admin.css') ?>">
<?php $errors=session('errors')??[];$stock=(int)($inventario['stock']??0);$imgs=(new \App\Models\ProductImageModel())->byProducto((int)$producto['id']);$previewUrl=$producto['imagen_url']?:base_url('assets/placeholder-product.png'); ?>
<main class="commerce-page"><header class="commerce-page-heading"><div><p class="commerce-eyebrow">CATÁLOGO / EDICIÓN</p><h1><?= esc($producto['nombre']) ?></h1><p>Actualiza la identidad y las imágenes sin perder el contexto comercial del producto.</p></div><a href="<?= site_url('productos') ?>">Volver al catálogo →</a></header>
<?php if($errors): ?><section class="commerce-errors" role="alert"><strong>Revisa la información indicada</strong><ul><?php foreach($errors as $error): ?><li><?= esc($error) ?></li><?php endforeach ?></ul></section><?php endif ?>
<form method="post" action="<?= site_url('productos/editar/'.$producto['id']) ?>" class="commerce-form-layout" novalidate><?= csrf_field() ?><div class="commerce-form-main">
<section class="commerce-card"><div class="commerce-section-heading"><div><p class="commerce-eyebrow">01 / IDENTIDAD</p><h2>Información principal</h2></div><span class="commerce-product-code"><?= esc($producto['sku']) ?></span></div><div class="commerce-fields"><label>SKU<input name="sku" maxlength="50" value="<?= esc($producto['sku']) ?>" required><small>Debe permanecer único.</small></label><label>Nombre<input name="nombre" maxlength="150" value="<?= esc($producto['nombre']) ?>" required><small>Enlace actual: <?= esc($producto['slug']??'sin definir') ?></small></label><label class="is-wide">Descripción<textarea name="descripcion" rows="4"><?= esc($producto['descripcion']) ?></textarea></label><label class="is-wide">URL de imagen<input id="imagen_url" name="imagen_url" value="<?= esc($producto['imagen_url']??'') ?>" placeholder="https://.../producto.webp"><small>Se utiliza como respaldo cuando no hay una imagen local principal.</small></label><div class="commerce-image-preview"><img id="preview-img" data-fallback="<?= base_url('assets/placeholder-product.png') ?>" src="<?= esc($previewUrl) ?>" alt="Vista previa"><div><strong>Vista previa de respaldo</strong><p>La galería se administra en la sección inferior.</p></div></div></div></section>
<section class="commerce-card"><div class="commerce-section-heading"><div><p class="commerce-eyebrow">02 / GALERÍA</p><h2>Imágenes del producto</h2></div><span class="commerce-gallery-count"><?= count($imgs) ?> imagen(es)</span></div>
<?php if(!$imgs): ?><div class="commerce-gallery-empty">Aún no hay imágenes locales. Selecciona archivos para completar la ficha visual.</div><?php else: ?><div class="commerce-gallery"><?php foreach($imgs as $im): ?><article><img src="<?= base_url(esc($im['thumb_path']?:$im['path'])) ?>" alt="<?= esc($im['alt']??$producto['nombre']) ?>"><div><span class="commerce-status <?= $im['is_primary']?'is-active':'is-inactive' ?>"><?= $im['is_primary']?'Principal':'Secundaria' ?></span><small>#<?= (int)$im['id'] ?></small></div><div class="commerce-gallery-actions"><form method="post" action="<?= site_url('productos/'.$producto['id'].'/imagenes/'.$im['id'].'/principal') ?>"><?= csrf_field() ?><button <?= $im['is_primary']?'disabled':'' ?>>Hacer principal</button></form><form method="post" action="<?= site_url('productos/'.$producto['id'].'/imagenes/'.$im['id'].'/eliminar') ?>" data-delete-image><?= csrf_field() ?><button>Eliminar</button></form></div></article><?php endforeach ?></div><?php endif ?>
<div class="commerce-uploader"><label>Nuevas imágenes<input id="edit-files" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" multiple><small>JPG, PNG o WebP; máximo 4 MB por archivo.</small></label><div id="edit-previews" class="commerce-thumbnails"></div><div><button id="btn-upload" class="commerce-primary" type="button">Subir seleccionadas</button><span id="upload-msg" role="status"></span></div></div></section></div>
<aside class="commerce-form-side"><section class="commerce-card commerce-side-card"><p class="commerce-eyebrow">03 / CONFIGURACIÓN</p><h2>Datos provisionales</h2><p>Compatibilidad temporal con el inventario anterior.</p><label>Precio base ($)<input type="number" step="0.01" min="0" name="precio_base" value="<?= number_format((float)$producto['precio_base'],2,'.','') ?>" required></label><label>Stock heredado<input type="number" min="0" step="1" name="stock" value="<?= $stock ?>"></label><label class="commerce-switch"><input type="checkbox" name="is_activo" value="1" <?= $producto['is_activo']?'checked':'' ?>><span></span><div><strong>Producto activo</strong><small>Disponible para procesos autorizados.</small></div></label></section><a class="commerce-secondary" href="<?= site_url('productos/'.$producto['id'].'/presentaciones') ?>">Administrar presentaciones →</a><div class="commerce-submit"><button class="commerce-primary" type="submit">Guardar cambios</button><a href="<?= site_url('productos') ?>">Cancelar</a></div></aside></form></main>
<script>window.productEdit={id:<?= (int)$producto['id'] ?>,uploadUrl:<?= json_encode(site_url('productos/'.$producto['id'].'/imagenes/subir')) ?>,csrfName:<?= json_encode(csrf_token()) ?>,csrfHash:<?= json_encode(csrf_hash()) ?>};</script><script src="<?= base_url('assets/vendor/sweetalert2/sweetalert2.min.js') ?>"></script><script src="<?= base_url('assets/js/product-edit.js') ?>"></script>
<?= $this->endSection() ?>
